### ISSUE TITLE
Supprt latest Kinetic (v5+)

### ISSUE THREAD

**Issue by mcintyre321** [fizmo/knockout-kinetic#4]
I've just been trying to get this to work with the latest version of Kinetic, but the example page just fails without drawing anything, and unfortunately no errors either. Thanks though, this library looks neat!

**Comment by mcintyre321** [comment]
Hi again.

I got this working with newer versions of Kinetic JS (it needed a minor tweak so that a new div is created for the stage elements container), and also discovered an actively maintained fork of Kinetic, called Konvajs.

My fork is here
https://github.com/mcintyre321/knockout-konva

Thanks again for creating this project!

**Comment by christophercurrie** [comment]
That sounds great. I'll go ahead and leave a note in the README pointing folks to your fork.
